account_id  = "88e970e7c66a206dc1d32ad757af81c5"
main        = "dist/worker.js"
name        = "mr-cicale"
workers_dev = true

[build]
  command = "yarn install && yarn build"

[triggers]
  crons = ["*	22	*	*	*	"]
